### ISSUE TITLE
Github Releases jars are broken

### ISSUE THREAD

**Issue by MetallicGoat** [PaperMC/codebook#29]
The codebook jars attached in the GitHub releases are missing their manifest's (they don't run). Cloning the project and using Intellij to build it works fine.

![image](https://github.com/PaperMC/codebook/assets/66706505/a43e26a8-b98d-440f-a15b-8a6526f71c10)

**Comment by MiniDigger** [comment]
https://github.com/PaperMC/codebook/releases/download/v1.0.9/codebook-cli-1.0.9-all.jar works as expected now
